apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xrs.example.crossplane.io
spec:
  conversion:
    strategy: None
  group: example.crossplane.io
  names:
    categories:
    - crossplane
    - composite
    kind: XR
    listKind: XRList
    plural: xrs
    singular: xr
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.compositionRef.name
      name: COMPOSITION
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: XR is the Schema for the XR API.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            description: XRSpec defines the desired state of XR.
            properties:
              claimRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - apiVersion
                - kind
                - namespace
                - name
                type: object
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionUpdatePolicy:
                default: Automatic
                enum:
                - Automatic
                - Manual
                type: string
              publishConnectionDetailsTo:
                properties:
                  configRef:
                    default:
                      name: default
                    properties:
                      name:
                        type: string
                    type: object
                  metadata:
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              resourceRefs:
                items:
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
                x-kubernetes-list-type: atomic
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
            type: object
          status:
            description: XRStatus defines the observed state of XR.
            properties:
              test:
                description: Freeform field containing test data
                items:
                  type: object
                type: array
                x-kubernetes-preserve-unknown-fields: true
              claimConditionTypes:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
